CREATE TABLE invoices (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT         NOT NULL UNIQUE REFERENCES orders(id),
    invoice_number  VARCHAR(255)   NOT NULL UNIQUE,
    amount          NUMERIC(10, 2) NOT NULL,
    issued_at       TIMESTAMP WITH TIME ZONE    NOT NULL
);